{% set name = "gtk" %}
{% set version = "4.12.1" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: gtk4  # note customization
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: b8b61d6cf94fac64bf3a0bfc7af137c9dd2f8360033fdeb0cfe9612b77a99a72
  patches:
    - macos-before-10.13.patch  # [osx]
    # compile issue fixed in https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6208
    # but it seems that this fix won't make it into the 4.12 series
    - macos-backport-6208.patch  # [osx]

build:
  number: 5
  run_exports:
    - {{ pin_subpackage('gtk4', max_pin='x') }}
    # gtk apps need at least a default icon set for fallback
    - adwaita-icon-theme
  missing_dso_whitelist:
    - /usr/lib/libcups.2.dylib    # [osx]

requirements:
  build:
    - meson
    - ninja
    - gobject-introspection
    - packaging  # workaround: this is needed for glib's gdbus-codegen
    - pkg-config
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libegl-devel') }}  # [linux]
    - cairo  # [build_platform != target_platform]
    - epoxy  # [build_platform != target_platform]
    - freetype  # [build_platform != target_platform]
    - gdk-pixbuf  # [build_platform != target_platform]
    - gettext  # [build_platform != target_platform]
    - glib  # [build_platform != target_platform]
    - harfbuzz  # [build_platform != target_platform]
    - libtiff  # [build_platform != target_platform]
    - libpng  # [build_platform != target_platform]
    - libjpeg-turbo  # [build_platform != target_platform]
    - zlib  # [build_platform != target_platform]
    - libgraphene  # [build_platform != target_platform]
    - pango  # [build_platform != target_platform]
  host:
    - cairo
    - epoxy
    - freetype
    - gdk-pixbuf
    - gettext  # [osx]
    - glib
    - harfbuzz
    - libtiff
    - libpng
    - libjpeg-turbo
    - zlib
    - libgraphene
    - libcups  # [linux]
    - libiconv  # [win]
    - pango
    - xorg-libice  # [linux]
    - xorg-libsm  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxcomposite  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxrender  # [linux]
    - xorg-libxtst  # [linux]
    - xorg-xineramaproto  # [linux]
    - xorg-xproto  # [linux]
  run:
    - hicolor-icon-theme
    - pango
    - libgraphene
    - fribidi
    - fontconfig
    - {{ pin_compatible('libcups') }}  # [linux]
    # The post-links scripts uses gio-querymodules from glib-tools
    - glib-tools
    - xorg-libx11  # [linux]
    - xorg-libxcomposite  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-xineramaproto  # [linux]
    - xorg-xproto  # [linux]

test:
  requires:
    - pygobject
  commands:
    # check that the binaries can run
    - gtk4-encode-symbolic-svg --help
    - gtk4-launch --help  # [unix]
    - gtk4-update-icon-cache --help
    # other binaries require a display, check that they get installed
    {% set cmds = ["gtk4-builder-tool", "gtk4-query-settings"] %}
    {% for cmd in cmds %}
    - command -v {{ cmd }}  # [unix]
    - where {{ cmd }}  # [win]
    {% endfor %}

    # verify that (some) headers get installed
    - test -f $PREFIX/include/gtk-4.0/gdk/gdk.h  # [unix]
    - test -f $PREFIX/include/gtk-4.0/gsk/gsk.h  # [unix]
    - test -f $PREFIX/include/gtk-4.0/gtk/gtk.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\gtk-4.0\\gdk\\gdk.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\gtk-4.0\\gsk\\gsk.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\gtk-4.0\\gtk\\gtk.h exit 1  # [win]

    # verify that pkgconfig files get installed
    {% set pcs = ["gtk4"] %}
    {% set pcs = pcs + ["gtk4-unix-print"] %}  # [unix]
    {% set pcs = pcs + ["gtk4-x11"] %}  # [linux]
    {% set pcs = pcs + ["gtk4-macos"] %}  # [osx]
    {% set pcs = pcs + ["gtk4-win32"] %}  # [win]
    {% for pc in pcs %}
    - test -f $PREFIX/lib/pkgconfig/{{ pc }}.pc  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\{{ pc }}.pc exit 1  # [win]
    {% endfor %}
    # check gi typelibs
    {% set gis = ["Gdk-4.0", "Gsk-4.0", "Gtk-4.0"] %}
    {% for gi in gis %}
    - test -f $PREFIX/lib/girepository-1.0/{{ gi }}.typelib    # [unix]
    - if not exist %PREFIX%\Library\lib\girepository-1.0\{{ gi }}.typelib exit 1         # [win]
    {% endfor %}


about:
  home: http://www.gtk.org/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Version 4 of the Gtk+ graphical toolkit
  description: |
    GTK is a multi-platform toolkit for creating graphical user interfaces.
    Offering a complete set of widgets, GTK is suitable for projects ranging
    from small one-off projects to complete application suites.
  doc_url: https://developer.gnome.org/gtk4/
  dev_url: https://gitlab.gnome.org/GNOME/gtk

extra:
  recipe-maintainers:
    - ryanvolz
    - pkgw
    - tschoonj
